name: Archive Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    paths:
      - 'cmd/archive-service/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile.archive'
      - '.github/workflows/archive-service-ci-cd.yml'
  pull_request:
    branches: [master, main]

jobs:
  cicd:
    uses: ./.github/workflows/reusable-service-cicd.yml
    with:
      service-name: archive-service
      dockerfile: Dockerfile.archive
      min-coverage: 20
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
