name: Scraper Service CI/CD

on:
  workflow_dispatch:
  push:
    branches: [master, main]
    paths:
      - 'cmd/scraper-service/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile.scraper'
      - '.github/workflows/scraper-service-ci-cd.yml'
  pull_request:
    branches: [master, main]

jobs:
  cicd:
    uses: ./.github/workflows/reusable-service-cicd.yml
    with:
      service-name: scraper-service
      dockerfile: Dockerfile.scraper
      min-coverage: 20
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
